name: "Has Changes"
description: "Check if a git repository has uncommitted changes"
branding:
  icon: "info"
  color: "yellow"
inputs:
  workingdirectory:
    description: "Arguments to the `git status` command."
    required: false
    default: "."
outputs:
  changed:
    description: "Whether or not there are uncommitted changes in the folder"
runs:
  using: "docker"
  image: "Dockerfile"
